<a href="https://colab.research.google.com/github/Dullard-boy/Hamoye-Data-Science-Summer-Internship/blob/main/Stage_C_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import numpy as np
data= pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')

In [18]:
data=data.drop(columns=['stab'])

In [19]:
x= data.drop(columns=['stabf'])
y= data['stabf']
y= y.replace(['unstable','stable'],[0,1])
y=np.array(y)
y=y.reshape(-1,1)

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=1)

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
y_train=scaler.fit_transform(y_train)
x_test=scaler.fit_transform(x_test)

In [22]:
from sklearn.preprocessing import LabelEncoder
lbl=LabelEncoder()
y_train=lbl.fit_transform(y_train)
y_train

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 0, 0, 1])

In [23]:
from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier(random_state=1)
clf.fit(x_train,y_train)
predicted_values=clf.predict(x_test)

In [24]:
from sklearn.ensemble import ExtraTreesClassifier
xclf=ExtraTreesClassifier(random_state=1)
xclf.fit(x_train,y_train)
xpredicted_values=xclf.predict(x_test)

In [25]:
from xgboost import XGBClassifier
xgb=XGBClassifier(random_state=1)
xgb.fit(x_train,y_train)
xgb_values=xgb.predict(x_test)

In [26]:
xgb_values

array([0, 0, 1, ..., 1, 0, 0])

In [27]:
from lightgbm import LGBMClassifier
lgbm=LGBMClassifier(random_state=1)
lgbm.fit(x_train,y_train)
lgbm_values=lgbm.predict(x_test)

In [28]:
lgbm_values

array([0, 0, 1, ..., 1, 0, 0])

In [29]:
from sklearn.metrics import accuracy_score, precision_score,recall_score, f1_score

In [30]:
clf_accuracy=accuracy_score(y_test,predicted_values)
print('Random Forest Accuracy:', clf_accuracy)

Random Forest Accuracy: 0.926


In [31]:
xclf_accuracy=accuracy_score(y_test,xpredicted_values)
print('Extra Trees Accuracy:', xclf_accuracy)

Extra Trees Accuracy: 0.922


In [33]:
xgb_accuracy=accuracy_score(y_test,xgb_values)
print('XGBoost Accuracy:', xgb_accuracy)

XGBoost Accuracy: 0.919


In [34]:
lgbm_accuracy=accuracy_score(y_test,lgbm_values)
print('Light XGBoost Accuracy:', lgbm_accuracy)

Light XGBoost Accuracy: 0.9355
